### ISSUE TITLE
Failed to build 

### ISSUE THREAD

**Issue by sshukun** [CoHDI/composable-resource-operator#1]
I was trying to install the operator into my k8s cluster but failed at the first step which is the CRD installation. 

The error log is:
```
$ make install                                                                                                                                       
test -s /home/member/go/src/composable-resource-operator/bin/controller-gen && /home/member/go/src/composable-resource-operator/bin/controller-gen --version | grep -q v0.12.0 || \
GOBIN=/home/member/go/src/composable-resource-operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.12.0
/home/member/go/src/composable-resource-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa0ba9e]

goroutine 153 [running]:
go/types.(*Checker).handleBailout(0xc00028b000, 0xc000d39d40)
        /usr/local/go/src/go/types/check.go:367 +0x88
panic({0xbc6180?, 0x12b0cc0?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0xdc1618, 0x12b9420})
        /usr/local/go/src/go/types/sizes.go:228 +0x31e
go/types.(*Config).sizeof(...)
        /usr/local/go/src/go/types/sizes.go:333
go/types.representableConst.func1({0xdc1618?, 0x12b9420?})
        /usr/local/go/src/go/types/const.go:76 +0x9e
go/types.representableConst({0xdc79b0, 0x1285540}, 0xc00028b000, 0x12b9420, 0xc000d394b0)
        /usr/local/go/src/go/types/const.go:92 +0x192
go/types.(*Checker).representation(0xc00028b000, 0xc0010ff1c0, 0x12b9420)
        /usr/local/go/src/go/types/const.go:256 +0x65
go/types.(*Checker).implicitTypeAndValue(0xc00028b000, 0xc0010ff1c0, {0xdc1640, 0xc00029ed20})
        /usr/local/go/src/go/types/expr.go:375 +0x30d
go/types.(*Checker).assignment(0xc00028b000, 0xc0010ff1c0, {0xdc1640, 0xc00029ed20}, {0xc93832, 0x14})
        /usr/local/go/src/go/types/assignments.go:52 +0x2e5
go/types.(*Checker).initConst(0xc00028b000, 0xc0010d2e40, 0xc0010ff1c0)
        /usr/local/go/src/go/types/assignments.go:126 +0x336
go/types.(*Checker).constDecl(0xc00028b000, 0xc0010d2e40, {0xdc4288, 0xc000ebc160}, {0xdc4288, 0xc000ebc180}, 0x0)
        /usr/local/go/src/go/types/decl.go:490 +0x348
go/types.(*Checker).objDecl(0xc00028b000, {0xdcd098, 0xc0010d2e40}, 0x0)
        /usr/local/go/src/go/types/decl.go:191 +0xa49
go/types.(*Checker).packageObjects(0xc00028b000)
        /usr/local/go/src/go/types/resolver.go:693 +0x4dd
go/types.(*Checker).checkFiles(0xc00028b000, {0xc000e40ba0, 0x5, 0x5})
        /usr/local/go/src/go/types/check.go:408 +0x1a5
go/types.(*Checker).Files(...)
        /usr/local/go/src/go/types/check.go:372
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck(0xc0002cb440, 0xc000805920)
        /home/member/go/pkg/mod/sigs.k8s.io/controller-tools@v0.12.0/pkg/loader/loader.go:286 +0x36a
sigs.k8s.io/controller-tools/pkg/loader.(*Package).NeedTypesInfo(0xc000805920)
        /home/member/go/pkg/mod/sigs.k8s.io/controller-tools@v0.12.0/pkg/loader/loader.go:99 +0x39
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc000788780, 0xc000805920)
        /home/member/go/pkg/mod/sigs.k8s.io/controller-tools@v0.12.0/pkg/loader/refs.go:268 +0x2b7
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0x52?)
        /home/member/go/pkg/mod/sigs.k8s.io/controller-tools@v0.12.0/pkg/loader/refs.go:262 +0x53
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check in goroutine 130
        /home/member/go/pkg/mod/sigs.k8s.io/controller-tools@v0.12.0/pkg/loader/refs.go:260 +0x1c5
make: *** [Makefile:100: manifests] Error 2

```

The OS I am using is:
```
$ cat /etc/lsb-release                                                                                                                               
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
```

The version of kubernetes is:
```
$ kubectl version                                                                                                                                   
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1
```

The version of Golang is:
```
$ go version                                                                                                                                          
go version go1.22.0 linux/amd64
```

**Comment by mgazz** [comment]
Hello @sshukun, thank you for trying the operator. Locally I built it with `go version go1.21.5 darwin/arm64` on Mac and it terminated correctly. I will bump my version to `go1.22.0 linux/amd64` and check if I can replicate the error. 

Could you try with version `1.21.5` on your side and check if the build terminates successfully?

**Comment by mgazz** [comment]
I confirm that I can replicate the error with go `1.22.0`

```
└❯make
mkdir -p /Users/mgazz/workspace/test-operator/test/composable-resource-operator/bin
test -s /Users/mgazz/workspace/test-operator/test/composable-resource-operator/bin/controller-gen && /Users/mgazz/workspace/test-operator/test/composable-resource-operator/bin/controller-gen --version | grep -q v0.12.0 || \
        GOBIN=/Users/mgazz/workspace/test-operator/test/composable-resource-operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.12.0
go: downloading sigs.k8s.io/controller-tools v0.12.0
go: downloading github.com/spf13/cobra v1.7.0
go: downloading github.com/fatih/color v1.15.0
go: downloading k8s.io/apimachinery v0.27.1
go: downloading k8s.io/api v0.27.1
go: downloading k8s.io/apiextensions-apiserver v0.27.1
go: downloading golang.org/x/tools v0.8.0
go: downloading github.com/gobuffalo/flect v1.0.2
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.17
go: downloading golang.org/x/net v0.9.0
go: downloading github.com/go-logr/logr v1.2.3
go: downloading golang.org/x/sys v0.7.0
go: downloading golang.org/x/mod v0.10.0
go: downloading golang.org/x/text v0.9.0
/Users/mgazz/workspace/test-operator/test/composable-resource-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x103396c30]

goroutine 72 [running]:
go/types.(*Checker).handleBailout(0x14000aef200, 0x140009f1d18)
        /Users/mgazz/.gvm/gos/go1.22.0/src/go/types/check.go:367 +0x9c
panic({0x103671380?, 0x103c0bf10?})
        /Users/mgazz/.gvm/gos/go1.22.0/src/runtime/panic.go:770 +0x124
go/types.(*StdSizes).Sizeof(0x0, {0x10373bfb0, 0x103c146a0})
        /Users/mgazz/.gvm/gos/go1.22.0/src/go/types/sizes.go:228 +0x320
go/types.(*Config).sizeof(...)
        /Users/mgazz/.gvm/gos/go1.22.0/src/go/types/sizes.go:333
go/types.representableConst.func1({0x10373bfb0?, 0x103c146a0?})
        /Users/mgazz/.gvm/gos/go1.22.0/src/go/types/const.go:76 +0x9c
go/types.representableConst({0x103742210, 0x103be0800}, 0x14000aef200, 0x103c146a0, 0x140009f1468)
        /Users/mgazz/.gvm/gos/go1.22.0/src/go/types/const.go:92 +0x138
go/types.(*Checker).representation(0x14000aef200, 0x14000e78a80, 0x103c146a0)
        /Users/mgazz/.gvm/gos/go1.22.0/src/go/types/const.go:256 +0x68
go/types.(*Checker).implicitTypeAndValue(0x14000aef200, 0x14000e78a80, {0x10373bfd8, 0x1400031af50})
        /Users/mgazz/.gvm/gos/go1.22.0/src/go/types/expr.go:375 +0x340
go/types.(*Checker).assignment(0x14000aef200, 0x14000e78a80, {0x10373bfd8, 0x1400031af50}, {0x1034af8e0, 0x14})
        /Users/mgazz/.gvm/gos/go1.22.0/src/go/types/assignments.go:52 +0x23c
go/types.(*Checker).initConst(0x14000aef200, 0x14000e1ea20, 0x14000e78a80)
        /Users/mgazz/.gvm/gos/go1.22.0/src/go/types/assignments.go:126 +0x304
go/types.(*Checker).constDecl(0x14000aef200, 0x14000e1ea20, {0x10373eb80, 0x14001054220}, {0x10373eb80, 0x14001054240}, 0x0)
        /Users/mgazz/.gvm/gos/go1.22.0/src/go/types/decl.go:490 +0x298
go/types.(*Checker).objDecl(0x14000aef200, {0x103747298, 0x14000e1ea20}, 0x0)
        /Users/mgazz/.gvm/gos/go1.22.0/src/go/types/decl.go:191 +0x84c
go/types.(*Checker).packageObjects(0x14000aef200)
        /Users/mgazz/.gvm/gos/go1.22.0/src/go/types/resolver.go:693 +0x468
go/types.(*Checker).checkFiles(0x14000aef200, {0x1400101a000, 0x5, 0x5})
        /Users/mgazz/.gvm/gos/go1.22.0/src/go/types/check.go:408 +0x164
go/types.(*Checker).Files(...)
        /Users/mgazz/.gvm/gos/go1.22.0/src/go/types/check.go:372
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck(0x1400036d470, 0x14000702ba0)
        /Users/mgazz/.gvm/pkgsets/go1.22.0/global/pkg/mod/sigs.k8s.io/controller-tools@v0.12.0/pkg/loader/loader.go:286 +0x2d8
sigs.k8s.io/controller-tools/pkg/loader.(*Package).NeedTypesInfo(0x14000702ba0)
        /Users/mgazz/.gvm/pkgsets/go1.22.0/global/pkg/mod/sigs.k8s.io/controller-tools@v0.12.0/pkg/loader/loader.go:99 +0x44
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0x14000bb46c0, 0x14000702ba0)
        /Users/mgazz/.gvm/pkgsets/go1.22.0/global/pkg/mod/sigs.k8s.io/controller-tools@v0.12.0/pkg/loader/refs.go:268 +0x304
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0x70?)
        /Users/mgazz/.gvm/pkgsets/go1.22.0/global/pkg/mod/sigs.k8s.io/controller-tools@v0.12.0/pkg/loader/refs.go:262 +0x58
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check in goroutine 87
        /Users/mgazz/.gvm/pkgsets/go1.22.0/global/pkg/mod/sigs.k8s.io/controller-tools@v0.12.0/pkg/loader/refs.go:260 +0x230
make: *** [manifests] Error 2
```

**Comment by sshukun** [comment]
@mgazz , after switched to go 1.21.5, the build completed successfully. 
Thanks for your reply :)

**Comment by mgazz** [comment]
No problem. I will close this issue.
